/**
 * MIPT Service API
 * This is MIPT microservice
 *
 * OpenAPI spec version: 0.1
 * Contact: support@digitory.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelsQuestionInterface } from './modelsQuestionInterface';

export interface ModelsConfigInterface { 
    creatorId?: string;
    expirationDate?: string;
    id?: string;
    publicToken?: string;
    questions?: Array<ModelsQuestionInterface>;
    title?: string;
}